[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

# Hedera Network Configuration
[rpc_endpoints]
# Hedera Testnet
hedera_testnet = "https://testnet.hashio.io/api"
testnet = "https://testnet.hashio.io/api"

# Hedera Mainnet
hedera_mainnet = "https://mainnet.hashio.io/api"
mainnet = "https://mainnet.hashio.io/api"

# Local Hedera (for development)
hedera_local = "http://localhost:7546"

[etherscan]
# Hedera Testnet
hedera_testnet = { key = "${ETHERSCAN_API_KEY}", chain = 296, url = "https://hashscan.io/testnet/" }
testnet = { key = "${ETHERSCAN_API_KEY}", chain = 296, url = "https://hashscan.io/testnet/" }

# Hedera Mainnet
hedera_mainnet = { key = "${ETHERSCAN_API_KEY}", chain = 295, url = "https://hashscan.io/mainnet/" }
mainnet = { key = "${ETHERSCAN_API_KEY}", chain = 295, url = "https://hashscan.io/mainnet/" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
